name: Measure Code Coverage

on:
  push:
    branches: ["main", "api"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  measure-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install System Dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install libasound-dev portaudio19-dev python3-all-dev espeak -y
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install portaudio
          fi
        shell: bash
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies using Poetry
        run: poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest --cov=aswe --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
